# Section 1: Motivation

Lists are great for storing small amounts of one-dimensional data. 

However, they can't be used directly with arithmetic operators such as ($+$, $-$, $*$, $/$, …)


In [2]:
a= [5, 10, 15, 20]
b=  [3, 6, 9, 12]
print(a+b)

[5, 10, 15, 20, 3, 6, 9, 12]


In [3]:
a = [5, 10, 15, 20]
b = [3, 6, 9, 12]
print([x + y for x, y in zip(a, b)])


[8, 16, 24, 32]


When it comes to efficient array manipulation, especially for multidimensional data, NumPy comes to the rescue.



<img src="images/numpy_image.png" width="532" height="213">


* Stands for Numerical Python
* Is the fundamental package required for high performance computing and data analysis
* NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.

<br>

Some advantage

* ndarray: 
    - It efficiently stores data in a contiguous block of memory, making it faster and more memory-efficient than built-in Python sequences. <br> Whenever you see “array,” “NumPy array,” or “ndarray” in the text, with few exceptions they all refer to the same thing: the ndarray object.
* Vectorization: 
    - NumPy Arrays are important because they enable you to express batch operations on data without writing any for loops. We call this vectorization. 
* Speed: 
 - Standard math functions for fast operations on entire arrays of data without having to write loops





In [4]:
import numpy as np
import sys

# Create a NumPy array and a Python list
my_arr = np.arange(1000000)
my_list = list(range(1000000))

# Check memory usage of NumPy array
numpy_memory_usage = sys.getsizeof(my_arr)

# Check memory usage of Python list
list_memory_usage = sys.getsizeof(my_list)

# Calculate efficiency as a percentage
efficiency_percentage = (1 - (numpy_memory_usage / list_memory_usage)) * 100

# Print results
print(f"Memory usage of NumPy array: {numpy_memory_usage} bytes")
print(f"Memory usage of Python list: {list_memory_usage} bytes")
print(f"NumPy is {efficiency_percentage:.2f}% more memory-efficient compared to a Python list.")


Memory usage of NumPy array: 4000112 bytes
Memory usage of Python list: 8000056 bytes
NumPy is 50.00% more memory-efficient compared to a Python list.


# Section 2: Getting Started with NumPy

To begin using NumPy, you first need to import the library using the import keyword

<pre><code class="python" language="python" style="font-size:0.8em">
import numpy as np
</code></pre>

In the code snippet above, we import NumPy and alias it as np. 


It is also possible to import NumPy and alias it with a different name. For example, you could import NumPy and alias it as mynumpy:

<br>
<pre><code class="python" language="python" style="font-size:0.8em">
import numpy as mynumpy
</code></pre>

However, it is recommended to use the alias np because it is the standard convention used by Python programmers and data scientists. This will make your code easier to read and understand for other Python programmers and data scientists.

# Section 3: ndarray

The core data structure in NumPy is the ndarray. Here are some key points about it:

* It's used for storing homogeneous data, meaning all elements are of the same data type.
* Every array must have a shape and a data type (dtype).
* It supports convenient slicing, indexing, and efficient vectorized computations.

In [5]:
# Remark, from here on, we will not import the numpy library anymore as it is already imported in the first cell of this notebook.

# To show that numpy has a shape, data type
# Create a 1D NumPy with zero elements
arr1 =  np.empty((0,))
print(arr1)
print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)


[]
float64
(0,)
1


## Creating NumPy Arrays

NumPy arrays can be created from Python lists. 

### Using a Python List
Creating a 1D NumPy Array:

In these lines of code, you are creating a NumPy array named 'arr' from a regular Python list named 'data'.




#### CREATING A 1D NUMPY ARRAY FROM PYTHON LIST


In [6]:
# Code Snippet 1
# The snippet below creates a 1D NumPy array from a Python list

data = [1, 2, 3, 4]
arr = np.array(data)

# Let's print the array and its type
print(f'The array: {arr}')
print(f'The shape of the array: {arr.shape}')
print(f'The array has a dimension of: {arr.ndim}')


The array: [1 2 3 4]
The shape of the array: (4,)
The array has a dimension of: 1


#### CREATING A 2D NUMPY ARRAY FROM PYTHON LIST

In [7]:
# Code Snippet 2
# The snippet below creates a 2D NumPy array from a Python list of lists

# Lets create 3 Python lists
data1 = [1, 2, 3]
data2 = [4, 5, 6]
data3 = [7, 8, 9]

# Now, let's create a list of lists
data_2d = [data1, data2, data3]

# Similarly, you can create the variable data as the commented line below


# data_2d = [[1, 2, 3],
#            [4, 5, 6],
#            [7, 8, 9]]

# Convert the 2D Python list to a NumPy array
arr_2d = np.array(data_2d)

# Let's print the array and its type
print(f'The array: \n {arr_2d}')
print(f'The shape of the array: {arr_2d.shape}')
print(f'The array has a dimension of: {arr_2d.ndim}')

The array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The shape of the array: (3, 3)
The array has a dimension of: 2


#### CREATING A 3D NUMPY ARRAY FROM PYTHON LIST


In [8]:
# Code Snippet 3
# The snippet below creates a 3D NumPy array from a Python list of lists of lists
data1 = [[1, 2, 3],
         [4, 5, 6]]
data2= [[7, 8, 9],
        [10, 11, 12]]
data3 = [[13, 14, 15],
         [16, 17, 18]]

# Now, let's create a list of lists of lists
data_3d = [data1, data2, data3]

# Convert the 3D Python list to a NumPy array
arr_3d = np.array(data_3d)

# Let's print the array and its type
print(f'The array: \n {arr_3d}')
print(f'The shape of the array: {arr_3d.shape}')
print(f'The array has a dimension of: {arr_3d.ndim}')

The array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
The shape of the array: (3, 2, 3)
The array has a dimension of: 3


### USING NUMPY BUILD IN FUNCTION

It is possible to create numpy array using build in function such as

<br>

| Type                 | Description                                          |
|----------------------|------------------------------------------------------|
| numpy.linspace       | When you need to generate an array of evenly spaced values over a specified range with a specific number of points. |
| numpy.random.rand    | Generate an array of random numbers sampled from a uniform distribution between 0 and 1. |
| numpy.random.randn   | Generate an array of random numbers sampled from a standard normal distribution (mean 0, standard deviation 1). May include negative values. |
| numpy.random.eye     | Create an identity matrix, which is a square matrix with ones on the main diagonal and zeros elsewhere.|
| numpy.arange         | Generate an array with evenly spaced values within a specified interval.|
| numpy.zeros          | Create an array filled with zeros.|
| numpy.ones           | Create an array filled with ones.|
| np.concatenate       | Concatenate (combine) multiple arrays along a specified axis. |




#### CREATING A NUMPY ARRAY FROM `numpy.linspace`

when you need to generate an array of evenly spaced values over a specified range with a specific number of points.


It's particularly useful when you want to create arrays for tasks like data visualization, plotting, interpolation, or when you need a set of values for mathematical functions.

<br>
<pre><code class="python" language="python" style="font-size:0.8em">
numpy.linspace(start, stop, num)
</code></pre>

<br>

| Keyword        | Description                                     |
| -------------- | ----------------------------------------------- |
| start          | The starting value of the sequence.             |
| stop           | The end value of the sequence, included if endpoint is set to true. |
| num            | The number of evenly spaced samples to generate. Default is 50. |


In [9]:
# Code Snippet 4
# The snippet below creates a 1D NumPy array using numpy.linspace
arr_1d=np.linspace(0, 10, 5)

# Let's print the array and its type
print(f'The array: \n {arr_1d}')
print(f'The shape of the array: {arr_1d.shape}')
print(f'The array has a dimension of: {arr_1d.ndim}')


The array: 
 [ 0.   2.5  5.   7.5 10. ]
The shape of the array: (5,)
The array has a dimension of: 1


Do you know how to generate 2D array using `numpy.linspace`?

#### CREATING A NUMPY ARRAY FROM `numpy.random.rand`

Generate an array of random numbers sampled from a uniform distribution between 0 and 1. generate random data in nd space

<br>
<pre><code class="python" language="python" style="font-size:0.8em">
numpy.random.rand(d0, d1, ..., dn)
</code></pre>

<br>

| Keyword               | Description                                       |
|-----------------------| ------------------------------------------------- |
| $d0$, $d1$, ..., $dn$ | The dimensions of the returned array.  |

<br>

Each value ($d0$, $d1$, ..., $dn$) should be a positive integer. If no arguments are given, a single Python float is returned, creating a $0D$ array.


##### CREATING A 1D NUMPY ARRAY FROM numpy.random.rand

To generate a 1D NumPy array using numpy.random.rand, you need to specify the number of elements in the array as the argument to the function.

In [10]:
# Code Snippet 5
# The snippet below creates a 1D NumPy array using numpy.random.rand

arr_1d = np.random.rand(5) # Here we specify the number of elements in the array to be 5
print(f'The array: \n {arr_1d}')
print(f'The shape of the array: {arr_1d.shape}')
print(f'The array has a dimension of: {arr_1d.ndim}')

The array: 
 [0.54289628 0.92534695 0.20585283 0.97737456 0.95170948]
The shape of the array: (5,)
The array has a dimension of: 1


##### CREATING A 2D NUMPY ARRAY FROM numpy.random.rand

To generate a $2D$ NumPy array using numpy.random.rand, you need to specify the number of rows and columns in the array as the argument to the function.The first integer specifies the number of rows in the array, and the second integer specifies the number of columns in the array


In [11]:
# Code Snippet 6
# The snippet below creates a 2D NumPy array using numpy.random.rand
arr_2d=np.random.rand(3, 4) # Here we specify the number of rows and columns in the array to be 3 and 4 respectively
print(f'The array: \n {arr_2d}')
print(f'The shape of the array: {arr_2d.shape}')
print(f'The array has a dimension of: {arr_2d.ndim}')


The array: 
 [[0.51496524 0.61028929 0.20530928 0.37054835]
 [0.45361025 0.37760755 0.53973641 0.55691498]
 [0.02695655 0.99068666 0.60298211 0.26141219]]
The shape of the array: (3, 4)
The array has a dimension of: 2


#### CREATING A 3D NUMPY ARRAY FROM numpy.random.rand
To generate a 3D array of random numbers, you can pass a tuple of three integers to the np.random.rand() function. 
<br>
The first integer specifies the number of rows in the array, the second integer specifies the number of columns in the array, and the third integer specifies the number of layers in the array. 


In [12]:
# Code Snippet 7
# The snippet below creates a 3D NumPy array using numpy.random.rand
arr_3d=np.random.rand(2, 3, 4) # Here we specify the number of rows, columns and depth in the array to be 2, 3 and 4 respectively
print(f'The array: \n {arr_3d}')
print(f'The shape of the array: {arr_3d.shape}')
print(f'The array has a dimension of: {arr_3d.ndim}')

The array: 
 [[[0.76676511 0.43799769 0.63859604 0.74902151]
  [0.60883156 0.21876201 0.6702968  0.75068047]
  [0.43719296 0.44537885 0.24582115 0.92000416]]

 [[0.44883719 0.85757029 0.1282188  0.3177679 ]
  [0.74138726 0.93315919 0.92707295 0.53240474]
  [0.71261761 0.23877214 0.9679164  0.55206912]]]
The shape of the array: (2, 3, 4)
The array has a dimension of: 3


### CREATING A NUMPY ARRAY FROM numpy.random.randn
Generate an array of random numbers sampled from a standard normal distribution (mean 0, standard deviation 1). Ada –ve value

<br>
<pre><code class="python" language="python" style="font-size:0.8em">
numpy.random.randn(d0, d1, ..., dn)
</code></pre>

<br>

| Keyword               | Description                                       |
|-----------------------| ------------------------------------------------- |
| $d0$, $d1$, ..., $dn$ | The dimensions of the returned array.  |

<br>



#### CREATING A 1D NUMPY ARRAY FROM numpy.random.randn

To generate a 1D NumPy array using numpy.random.randn, you need to specify the number of elements in the array as the argument to the function.

In [13]:
# Code Snippet 8
# The snippet below creates a 1D NumPy array using numpy.random.randn
arr_1d= np.random.randn(10) # Here we specify the number of elements in the array to be 10
print(f'The array: \n {arr_1d}')
print(f'The shape of the array: {arr_1d.shape}')
print(f'The array has a dimension of: {arr_1d.ndim}')

The array: 
 [-2.25966148 -0.85626021  0.27566605 -0.6123135   0.33848067  1.82711706
  0.54661544  1.92517421  0.50700042  0.50670689]
The shape of the array: (10,)
The array has a dimension of: 1


##### CREATING A 2D NUMPY ARRAY FROM numpy.random.randn

To generate a 2D NumPy array using numpy.random.randn, you need to specify the number of rows and columns in the array as the argument to the function.The first integer specifies the number of rows in the array, and the second integer specifies the number of columns in the array

In [14]:
# Code Snippet 9
# The snippet below creates a 2D NumPy array using numpy.random.randn
arr_2d=np.random.randn(3, 4) # Here we specify the number of rows and columns in the array to be 3 and 4 respectively   
print(f'The array: \n {arr_2d}')
print(f'The shape of the array: {arr_2d.shape}')
print(f'The array has a dimension of: {arr_2d.ndim}')

The array: 
 [[-0.13987219  0.63490458  2.53711004 -1.79332691]
 [ 1.84817365  0.8721086   1.9236083  -0.52174479]
 [-0.36074274 -1.21412615 -1.09266796  0.48662474]]
The shape of the array: (3, 4)
The array has a dimension of: 2


##### CREATING A 3D NUMPY ARRAY FROM numpy.random.randn
To generate a 3D array of random numbers, you can pass a tuple of three integers to the np.random.randn() function.

In [15]:
# Code Snippet 10
# The snippet below creates a 3D NumPy array using numpy.random.randn
arr_3d=np.random.randn(2, 3, 4) # Here we specify the number of rows, columns and depth in the array to be 2, 3 and 4 respectively
print(f'The array: \n {arr_3d}')
print(f'The shape of the array: {arr_3d.shape}')
print(f'The array has a dimension of: {arr_3d.ndim}')

The array: 
 [[[-1.70570408 -0.18272646  1.4174374  -1.65312179]
  [-1.40385095 -0.10555542  1.74270339 -0.24891971]
  [ 0.87573485  0.73162254 -0.50989037 -2.36965412]]

 [[-1.18321841  0.59951696 -0.92302531  1.65195443]
  [-1.12214971  0.43268359  0.70000484 -0.68268667]
  [-0.55781534  0.35070814 -1.71392444  0.33399565]]]
The shape of the array: (2, 3, 4)
The array has a dimension of: 3


### ARRAY DANGER ZONE

Must be dense, no holes.
Must be one type
Cannot combine arrays of different shape


In [17]:
np.ones([7,8])+np.ones([9,3])

ValueError: operands could not be broadcast together with shapes (7,8) (9,3) 

# Section 4: Basic Indexing and Slicing
Basic indexing and slicing is similar to Python lists.




In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0]) # Get the first element

1


To acess a slice of an array, you use the colon operator (:). The colon operator is used to specify the start and end indices of the slice.

The syntax for slicing is as follows:

<pre><code class="python" language="python" style="font-size:0.8em">
arr[start:end]
</code></pre>

<br>

| Keyword        | Description                                     |
| -------------- | ----------------------------------------------- |
| start          | The starting index of the slice.                |
| end            | The end index of the slice, excluded if endpoint is set to true. |


In [20]:
# Code Snippet 11
# The snippet below creates a 1D NumPy array and slices it
arr = np.arange(1, 10)

# The line below slices the array from index 2 to 5, and print the slice
print(arr[3:6]) # Get values in a range

[4 5 6]


## Integer Array Indexing

Integer array indexing allows you to select arbitrary items in an array based on their index.

The syntax for integer array indexing is as follows:

<pre><code class="python" language="python" style="font-size:0.8em">
arr[[i1, i2, i3, ..., in]]
</code></pre>

<br>

| Keyword        | Description                                     |
| -------------- | ----------------------------------------------- |
| $i1$, $i2$, ..., $in$ | The indices of the elements to be selected.  |


In [21]:
# Code Snippet 12   
# The snippet below creates a 1D NumPy array and slices it using integer array indexing
arr = np.arange(1, 10)
indices = [2, 4, 6] # Create a list of indices used to slice the array

# The line below slices the array using the indices list, and print the slice
print(arr[indices]) # Get values by index


[3 5 7]


## Boolean Array Indexing

Boolean array indexing allows you to select arbitrary items in an array based on a boolean mask.

The syntax for boolean array indexing is as follows:

<pre><code class="python" language="python" style="font-size:0.8em">
arr[bool_arr]
</code></pre>

<br>

| Keyword        | Description                                     |
| -------------- | ----------------------------------------------- |
| $bool\_arr$    | A boolean array that specifies which elements to select.  |


In [22]:
# Code Snippet 13
# The snippet below creates a 1D NumPy array and slices it using boolean array indexing
arr = np.arange(1, 10)
bool_arr = arr > 5 # Create a boolean array that specifies which elements to select

# The line below slices the array using the boolean array, and print the slice
print(arr[bool_arr]) # Get values by boolean array


[6 7 8 9]


## Multiple Dimensional Arrays

You can also slice multiple dimensional arrays. The syntax for slicing multiple dimensional arrays is as follows:
For multi-dimensional arrays, you can use a comma-separated tuple of indices or slices.


In [25]:
# Code Snippet 14
# The snippet below creates a 2D NumPy array and slices it

# Create a 2D array

            #   Col 0  1  2  
matrix = np.array([[5, 2, 7],   # Row 0
                   [4, 4, 6],   # Row 1
                   [8, 2, 3]])  # Row 2 


# Access an element
print(matrix[1, 2]) # Get a value from a 2D array

6


To slice row and column of a 2D array, you can use the following syntax:

In [40]:
# Code Snippet 15
# The snippet below creates a 2D NumPy array and slices it

# Create a 2D array

            #   Col 0  1  2 
matrix = np.array([[5, 1, 7],   # Row 0
                   [4, 4, 6],   # Row 1
                   [8, 2, 3]])  # Row 2
# Access a row and a column
print(matrix[0:2, 1:3])


[[1 7]
 [4 6]]


## Ellipsis Indexing
The ellipsis (...) can be used to index higher-dimensional arrays more flexibly.



More details can be found [documentation](https://python-reference.readthedocs.io/en/latest/docs/brackets/ellipsis.html)

In [58]:
# Code Snippet 16
import copy
arr = np.arange(10).reshape(2, 5)
arr_copy = copy.deepcopy(arr)
# For convenience, the arr variable is printed below
# [[0 1 2 3 4]
#  [5 6 7 8 9]]

print(arr[Ellipsis, 2]) 

# Instead of using the ellipsis, you can also use the following syntax
print(arr_copy [..., 2]) # You can read this as slice all ro

[2 7]
[2 7]


## Fancy Indexing
You can use combinations of these techniques for more complex indexing.

In [67]:
# Code Snippet 17
arr = np.array([1, 2, 3, 4, 5])
indices = np.array([0, 2])
print(f'The indices value {indices}')
mask = arr > 2
print(f'The mask value {mask}')
# Apply the mask first and then use indices
filtered_arr = arr[mask]
print(f'The filtered_arr value {filtered_arr}')

result = filtered_arr[indices]

print(result)

The indices value [0 2]
The mask value [False False  True  True  True]
The filtered_arr value [3 4 5]
[3 5]


# Section 5: Shaping

The are several way to reshape an array
reshape()
resize()
ravel()
flatten()
transpose()

While reshaping, the total number of element cannot change.

Reshape ()

In [68]:
# Code Snippet 18
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.reshape(6)

print(b)


[1 2 3 4 5 6]


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, -1))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


Resize()

The resize() function is similar to the reshape() function, but it does not require the new shape to be compatible with the original shape. If the new shape is not compatible, the resize() function will add or remove dimensions to the array as needed.



For example, the following code resizes a 2D array into a 3D array:

In [70]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.resize(3, 2)

print(a)


[[1 2]
 [3 4]
 [5 6]]


 The ravel() function flattens an array into a 1D array. This means that all the elements of the array are placed in a single row.
For example, the following code ravels a 2D array:


In [74]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.ravel()

print(b)
print(a)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


flatten()
The flatten() function is similar to the ravel() function, but it returns a copy of the flattened array. The ravel() function modifies the original array. cross check the accuracy of this statement


For example, the following code flattens a 2D array and saves it to a new array:


In [72]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a.flatten()

print(b)


[1 2 3 4 5 6]


transpose()


In [76]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = arr.transpose()
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [77]:
# An alternative way to transpose an array is to use the T attribute.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
transposed_arr = arr.T
print(transposed_arr)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# Section 6: Mathematical operators




Addition: + or add()
Subtraction: - or subtract()
Multiplication: * or multiply()
Division: / or divide()
Exponentiation: ** or power()
Modulus: % or mod()
Remainder: // or remainder()
Absolute value: abs()
Negation: -
Reciprocal: 1 / x or reciprocal()
Root: np.sqrt(x)
Trigonometric functions: sin(), cos(), tan(), arcsin(), arccos(), arctan()
Hyperbolic functions: sinh(), cosh(), tanh(), arcsinh(), arccosh(), arctanh()
Logarithmic functions: log(), log10(), np.log2(x)
Exponential functions: exp()
Power functions: pow(x, y)


## Arithmetic operations are element-wise

Arithmetic operations are element-wise

In [78]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)


[5 7 9]


# Section 7: Logical operator return a bool array



The following are some of the logical operators in NumPy:

>: Greater than
<: Less than
>=: Greater than or equal to
<=: Less than or equal to
==: Equal to
!=: Not equal to
and: Logical AND
or: Logical OR
not: Logical NOT


In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a > b

print(c)


[False False False]


In place operations modify the array


In NumPy, an in-place operation is an operation that modifies the original array rather than creating a new one. In-place operations are often denoted with the +=, -=, *=, /=, and **= operators.


For example, the following code creates an array a and then adds 1 to each element of the array using the += operator:


In [80]:
a = np.array([1, 2, 3])

a += 1  # The original array a is modified, and the new values are printed.


print(a)


[2 3 4]


# Section 8: upcasting


For example, the following code explicitly upcasts the array a to int16:


In [81]:
a = np.array([1, 2, 3], dtype=np.int8)

a = a.astype(np.int16)

print(a)


[1 2 3]
