In [ ]:
import numpy as np
import sys

my_arr = np.arange(1000000)
my_list = list(range(1000000))

# Check memory usage of NumPy array
numpy_memory_usage = sys.getsizeof(my_arr)
print(f"Memory usage of NumPy array: {numpy_memory_usage} bytes")

# Check memory usage of Python list
list_memory_usage = sys.getsizeof(my_list)
print(f"Memory usage of Python list: {list_memory_usage} bytes")

CREATING A 2D NUMPY ARRAY FROM PYTHON LIST

In [1]:
import numpy as np

# Create a 2D Python list
data_2d = [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]

# Convert the 2D Python list to a NumPy array
arr_2d = np.array(data_2d)

# Display the 2D NumPy array
print("2D NumPy Array:")
print(arr_2d)

2D NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# CREATING A 3D NUMPY ARRAY FROM PYTHON LIST

In [ ]:
import numpy as np

# Create a 3D Python list
data_3d = [[[1, 2, 3],
            [4, 5, 6]],

           [[7, 8, 9],
            [10, 11, 12]]]

# Convert the 3D Python list to a NumPy array
arr_3d = np.array(data_3d)

# Display the 3D NumPy array
print("3D NumPy Array:")
print(arr_3d)

In [2]:
import numpy as np

# Creating a 1D NumPy Array
arr_1d = np.arange(10)  # Creates a 1D array from 0 to 9
print("1D NumPy Array:")
print(arr_1d)

1D NumPy Array:
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Creating a 1D NumPy Array
arr_1d = np.arange(5,15,2)
print("1D NumPy Array:")
print(arr_1d)

1D NumPy Array:
[ 5  7  9 11 13]


In [6]:
import numpy as np
arr = np.linspace(10, 16, 5)
print(arr)

[10.  11.5 13.  14.5 16. ]


In [7]:
import numpy as np
print(np.random.rand(2, 2))

[[0.34590813 0.54590139]
 [0.09394015 0.35125857]]


In [13]:
print(np.random.rand(2,2,2,2,2))

[[[[[0.36519907 0.03084903]
    [0.68289848 0.52272888]]

   [[0.10630187 0.47814808]
    [0.14888334 0.20549683]]]


  [[[0.33905393 0.09846189]
    [0.12859467 0.97074255]]

   [[0.26658398 0.62412114]
    [0.8655281  0.00358722]]]]



 [[[[0.39362244 0.34095622]
    [0.0705317  0.72443718]]

   [[0.37480231 0.58029721]
    [0.76494958 0.37812368]]]


  [[[0.35136098 0.44575652]
    [0.90097729 0.26968975]]

   [[0.93304527 0.40715364]
    [0.17517483 0.43548671]]]]]


In [3]:
import numpy as np
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:

import numpy as np
arr = np.arange(10)

print(arr[np.newaxis, :])

[[0 1 2 3 4 5 6 7 8 9]]


In [4]:
cube = np.random.rand(3, 3, 3)
result = cube[..., 1]

In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, -1))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


Arithmetic operations are element-wise

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b

print(c)

[5 7 9]


The output array c has the same shape as the input arrays a and b. Each element of c is the sum of the corresponding elements of a and b.

Element-wise operations are very efficient in NumPy because they can be performed using vectorized operations. Vectorized operations are operations that are applied to each element of an array in a single pass. This is in contrast to looping operations, which iterate over each element of an array one at a time.

Vectorized operations are much faster than looping operations because they can take advantage of the parallel processing capabilities of modern CPUs. This is why NumPy is often used for scientific computing and machine learning applications, where speed is essential.

element-wise multiplication in NumPy

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.multiply(a, b)  # another alternative is c = a * b

print(c)

[ 4 10 18]


broadcasting mechanism:

In [9]:
a = np.array([1, 2, 3])
b = 4

c = a * b

print(c)

[ 4  8 12]


The broadcasting mechanism allows you to multiply an array with a scalar. In this case, the scalar 4 is broadcasted to the shape of the array a, resulting in an array of the same shape as a. The element-wise multiplication is then performed on the two arrays.